# Generated by Django 4.2.7 on 2023-11-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_code",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cost_per_item", models.DecimalField(decimal_places=2, max_digits=19)),
                ("quantity_in_stock", models.IntegerField()),
                ("quantity_sold", models.IntegerField()),
                ("sales", models.DecimalField(decimal_places=2, max_digits=19)),
                ("stock_date", models.DateField(auto_now_add=True)),
                ("last_sales_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("quantity_moved", models.IntegerField()),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_moved", models.DateField(auto_now=True)),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_location",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_location",
                        to="inventory.location",
                    ),
                ),
            ],
        ),
    ]
