# Generated by Django 5.0 on 2023-12-09 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmovement',
            old_name='quantity_moved',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='productmovement',
            name='transaction_type',
            field=models.CharField(choices=[('Stock Receipt', 'Stock Receipt'), ('Stock Transfer', 'Stock Transfer'), ('Stock Issue', 'Stock Issue')], default='Stock Receipt', max_length=15),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MovementLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('Stock Receipt', 'Stock Receipt'), ('Stock Transfer', 'Stock Transfer'), ('Stock Issue', 'Stock Issue')], default='Stock Receipt', max_length=15)),
                ('quantity', models.IntegerField()),
                ('balance_before_movement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_movement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_moved', models.DateField(auto_now=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location_ledger', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location_ledger', to='inventory.location')),
            ],
        ),
    ]
