# Generated by Django 5.0 on 2023-12-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_quantity_moved_productmovement_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementledger',
            name='product_movement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.productmovement'),
            preserve_default=False,
        ),
    ]
