# Generated by Django 5.0 on 2023-12-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movementledger_product_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
