# Generated by Django 5.0 on 2023-12-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementledger',
            name='balance_after_movement',
        ),
        migrations.RemoveField(
            model_name='movementledger',
            name='balance_before_movement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='balance',
        ),
    ]
