# Generated by Django 5.0 on 2023-12-09 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_movementledger_balance_after_movement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='inventory.location'),
        ),
    ]
