# Generated by Django 5.0 on 2023-12-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_productmovement_from_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovement',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='productmovement',
            name='transaction_type',
        ),
        migrations.CreateModel(
            name='ProductMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('Stock Receipt', 'Stock Receipt'), ('Stock Transfer', 'Stock Transfer'), ('Stock Issue', 'Stock Issue')], default='Stock Receipt', max_length=15)),
                ('quantity', models.IntegerField()),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_product', to='inventory.product')),
                ('product_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_items', to='inventory.productmovement')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='inventory.location')),
            ],
        ),
        migrations.DeleteModel(
            name='MovementLedger',
        ),
    ]
