# Generated by Django 5.0 on 2023-12-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_productmovement_from_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmovementitem',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='productmovement',
            name='transaction_type',
            field=models.CharField(choices=[('Stock Receipt', 'Stock Receipt'), ('Stock Transfer', 'Stock Transfer'), ('Stock Issue', 'Stock Issue')], default='Stock Receipt', max_length=15),
        ),
    ]
