# Generated by Django 5.0 on 2023-12-09 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_productmovementitem_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('Stock Receipt', 'Stock Receipt'), ('Stock Transfer', 'Stock Transfer'), ('Stock Issue', 'Stock Issue')], default='Stock Receipt', max_length=15)),
                ('quantity', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_moved', models.DateField(auto_now=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location_ledger', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('product_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productmovement')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location_ledger', to='inventory.location')),
            ],
        ),
    ]
